### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by osorensen** [DIDSR/WebXR-tools#11]
This relates to the following review item:

<img width="799" alt="image" src="https://github.com/DIDSR/WebXR-tools/assets/21175639/a535222c-e463-476d-be69-5726176fdcae">

I suggest creating a file `CONTRIBUTING.md` in the top level of the repository, describing all of this.

https://github.com/openjournals/joss-reviews/issues/6021

**Comment by brendanc490** [comment]
Thanks for pointing this out. We will use the issues feature on GitHub to allow for reporting bugs, errors, and asking questions. I added this to the documentation https://didsr.github.io/WebXR-tools/Custom/doc/contributing.html.

**Comment by osorensen** [comment]
Thanks!
