### ISSUE TITLE
README Improvement suggestions

### ISSUE THREAD

**Issue by codeling** [DIDSR/WebXR-tools#4]
In my review of [your JOSS submission](https://github.com/openjournals/joss-reviews/issues/6021), I noticed that the [review guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#documentation) state that the README should contain a high-level of the software documentation; in that regard it is currently a bit lacking I think.

I would propose the following changes:
  - extend the introductory sentence a little, such as adding a summary of the functionality of the pattern creator, and mentioning all potential user groups (as mentioned in the paper). 
  - add a link to the online version of the pattern creator (https://didsr.github.io/WebXR-tools/Custom/).
  - add a link to the  documentation (https://joss.readthedocs.io/en/latest/review_criteria.html).
  - add one sentence on possibility to run a local installation.

**Comment by brendanc490** [comment]
These are great points. I’ve updated the README to contain the links and a broad overview of the tool and its use case. I have also added a section about how to run the tool locally. https://github.com/DIDSR/WebXR-tools/blob/JOSS-Submission/README.md

**Comment by codeling** [comment]
Looks good.
I guess JOSS-Submission branch will soon be merged into main?

**Comment by brendanc490** [comment]
Yes, that's correct. When the review is complete we will merge this branch into main.

**Comment by malago86** [comment]
JOSS branch has been merged with the main branch now.
