### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by osorensen** [DIDSR/WebXR-tools#9]
Another comment on my JOSS review. I realize that the code is mainly meant to be run through the website https://didsr.github.io/WebXR-tools/, but it should be possible to also run this locally, for users wishing to do so. Could you please add a section in the README containing installation instructions.

This relates to the review item shown below:

<img width="770" alt="image" src="https://github.com/DIDSR/WebXR-tools/assets/21175639/7dbe76b4-6967-4ceb-8585-e7d0679a66d8">

https://github.com/openjournals/joss-reviews/issues/6021

**Comment by brendanc490** [comment]
This is a good point. I will add the instructions on how to run this tool locally. The steps here are to download the distribution and launch the index.html locally. I added them to the README. https://github.com/DIDSR/WebXR-tools/blob/JOSS-Submission/README.md

**Comment by osorensen** [comment]
Thanks, but the installation instructions for running locally did not work for me. Here is what I did:

## Step 1

I am on the `JOSS-Submission` branch, and run `open ./index.html`:

<img width="430" alt="image" src="https://github.com/DIDSR/WebXR-tools/assets/21175639/82e1e142-926b-4c59-b220-8e3970692e54">


## Step 2

I get to the frontpage:

<img width="1101" alt="image" src="https://github.com/DIDSR/WebXR-tools/assets/21175639/b78e250c-408d-4634-ae5b-821df069b371">

## Step 3

Clicking into any of the two options simply gives me a listing of the files in the directory

<img width="769" alt="image" src="https://github.com/DIDSR/WebXR-tools/assets/21175639/3d7ffac0-8223-4e03-8880-81ad9ea9a892">

Do I need anything else installed?

**Comment by brendanc490** [comment]
There was an error in the first index.html, thanks for pointing this out. I have updated that index.html so that it should now always open the tools, not their directory.

**Comment by osorensen** [comment]
Thanks, it works now
